CREATE DATABASE STUDENTAPI;

USE STUDENTAPI;

CREATE TABLE STUDENT(ID LONG PRIMARY KEY NOT NULL, NAME VARCHAR(30), EMAIL VARCHAR(30), PHONE VARCHAR(10), ROLL INTEGER, GRADE VARCHAR(10), SCHOOL VARCHAR(30));

INSERT INTO STUDENT VALUES(1, "VERONICA DONOVAN", "veronica@gmail.com", "998909878", 34, "Grade 10", "DAV");

SELECT * FROM STUDENT;
